model:
  num_classes: 8
  freeze_ratio: 0.7
  n_epochs: 100
data:
  batch_size: 32
  data_dir: images

trainer:
  accelerator: gpu
  logger: 
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: bg_cv
      name: resnet50_separate_augs
  max_epochs: 100
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: ${trainer.logger.init_args.name}_checkpoints
        monitor: val_f1
        filename: "{epoch:02d}-{val_f1:.3f}"
        mode: max